#include "ToyFileIO/ToyFileIO.h"
#include <iostream>
using namespace std;

int main(void) {
    cout << "Running tests of comparing XML's generated by LL(1) and LR(1)..." << endl;
    if (ToyFileIO::compareFiles("test_01_LL1.xml", "test_01_LR1.xml")) {
        cout << "Error: Different XML's of \"test_01.toy\" generated by LL(1) and LR(1)!" << endl;
        exit(EXIT_FAILURE);
    }
    cout << "Success!" << endl;
    if (ToyFileIO::compareFiles("test_02_LL1.xml", "test_02_LR1.xml")) {
        cout << "Error: Different XML's of \"test_02.toy\" generated by LL(1) and LR(1)!" << endl;
        exit(EXIT_FAILURE);
    }
    cout << "Success!" << endl;
    return 0;
}
